pipeline {
    agent none
    stages {
        stage('Build') {
            agent { 
                label 'Orion'
            }
            steps {
                cd /work/noaa/nems/zshrader
                export img=/work/noaa/epic-ps/role-epic-ps/containers/ubuntu20.04-intel-ue-landda-v1.1.0.img
                mkdir sandbox
                cd sandbox/
                ln -s /contrib/EPIC/landda/inputs .
                module load intel/2022.1.2 impi/2022.1.2
                singularity exec -H $PWD $img cp -r /opt/land-DA_workflow .
                cd land-DA_workflow/
            }
        }
        stage('Test on Orion') {
            agent { 
                label 'Orion'
            }
            steps {
                sed -i 's|hera.internal|orion.sing|g' settings_DA_cycle_gdas
                sed -i 's/da-cpu/epic/g' submit_cycle.sh
                export USE_SINGULARITY=yes
                source do_submit_test.sh

                }
            }
        stage('Build') {
            agent { 
                label 'Hera'
            }
            steps {
                export img=/scratch1/NCEPDEV/nems/role.epic/containers/ubuntu20.04-intel-ue-landda-v1.1.0.img
                mkdir sandbox
                cd sandbox/
                ln -s /scratch1/NCEPDEV/nems/role.epic/landda/inputs .
                module load intel/2022.1.2 impi/2022.1.2
                singularity exec -H $PWD $img cp -r /opt/land-DA_workflow .
                cd land-DA_workflow/
            }
        }
        stage('Test on Hera') {
            agent { 
                label 'Hera'
            }
            steps {
                sed -i 's|hera.internal|hera.sing|g' settings_DA_cycle_gdas
                sed -i 's/da-cpu/nems/g' submit_cycle.sh
                export USE_SINGULARITY=yes
                source do_submit_test.sh
                }
            }
        stage('Build') {
            agent { 
                label 'Jet'
            }
            steps {
                export img=/mnt/lfs4/HFIP/hfv3gfs/role.epic/containers/ubuntu20.04-intel-ue-landda-v1.1.0.img
                mkdir sandbox
                cd sandbox/
                ln -s /mnt/lfs4/HFIP/hfv3gfs/role.epic/landda/inputs .
                module load intel/2022.1.2 impi/2022.1.2
                singularity exec -H $PWD $img cp -r /opt/land-DA_workflow .
                cd land-DA_workflow/
            }
        }
        stage('Test on Jet') {
            agent { 
                label 'Jet'
            }
            steps {
                sed -i 's|hera.internal|jet.sing|g' settings_DA_cycle_gdas
                sed -i 's/da-cpu/h-nems/g' submit_cycle.sh
                export USE_SINGULARITY=yes
                source do_submit_test.sh
                }
            }
        stage('Build') {
            agent { 
                label 'Hercules'
            }
            steps {
                export img=/contrib/EPIC/containers/ubuntu20.04-intel-ue-landda-v1.1.0.img
                mkdir sandbox
                cd sandbox/
                ln -s /contrib/EPIC/landda/inputs .
                module load intel/2022.1.2 impi/2022.1.2
                singularity exec -H $PWD $img cp -r /opt/land-DA_workflow .
                cd land-DA_workflow/
            }
        }
        stage('Test on Hercules') {
            agent { 
                label 'Hercules'
            }
            steps {
                sed -i 's|hera.internal|hercules.sing|g' settings_DA_cycle_gdas
                sed -i 's/da-cpu/epic/g' submit_cycle.sh
                export USE_SINGULARITY=yes
                source do_submit_test.sh
                }
            }
