pipeline {
  agent none
  stages {
    stage('Land DA workflow') {
       agent {
        label 'built-in'   
       }
      steps {
        script {
          for (label in pullRequest.labels) {
            if ((label.matches("orion"))) {
                 env.CHOICE_NODE='orion'
            }  
            else if ((label.matches("hera"))) { 
                env.CHOICE_NODE='hera'
            }  
            else if ((label.matches("jet"))) {
                env.CHOICE_NODE='jet'
            } 
            else { 
                env.CHOICE_NODE='none'
            }
         }
// Why do I need another if..block, because it just works this way.

            if (CHOICE_NODE == 'orion') {
                echo "Starting up orion ${CHOICE_NODE}...this might take 5-10 minutes...please be patient."
               
            } 
             else if (CHOICE_NODE == 'jet') {
                echo "Starting up jet ${CHOICE_NODE}...this might take 5-10 minutes...please be patient."
            }
             else if (CHOICE_NODE == 'hera') {
                 echo "Starting up hera ${CHOICE_NODE}...this might take 5-10 minutes...please be patient."
            }
             else {
                echo "${CHOICE_NODE} is NOT a platform, moving on..."
            }
       }    
    }
  } 
  stage('Run Land DA Workflow on Orion') {
        agent {
          label "orion"
        }
        environment {
        ACCNR = 'nems'
        NODE_PATH = '/work/noaa/nems/zshrader/'
      }
      steps {
          
        cleanWs()
        checkout scm
        sh '''
        pwd
        export img=/work/noaa/epic-ps/role-epic-ps/containers/ubuntu20.04-intel-ue-landda-v1.1.0.img
        mkdir sandbox
        cd sandbox/
        ln -s /work/noaa/epic-ps/role-epic-ps/landda/inputs .
        module load intel/2022.1.2 impi/2022.1.2
        module load singularity/3.8.3 
        singularity exec -H $PWD $img cp -r /opt/land-DA_workflow .
        cd land-DA_workflow/
        sed -i 's|hera.internal|orion.sing|g' settings_DA_cycle_gdas
        sed -i 's/da-cpu/epic/g' submit_cycle.sh
        export USE_SINGULARITY=yes
        pwd
        ./do_submit_cycle.sh settings_DA_cycle_gdas
        '''
      }
    }    
    stage('Run Land DA Workflow on Jet') {
        agent {
          label "jet"
        }
        environment {
        ACCNR = 'h-nems'
        NODE_PATH = '/mnt/lfs4/HFIP/hfv3gfs/Zachary.Shrader/'
      }
      steps {
          
        cleanWs()
        checkout scm
        sh '''
        pwd
        export img=/mnt/lfs4/HFIP/hfv3gfs/role.epic/containers/ubuntu20.04-intel-ue-landda-v1.1.0.img
        mkdir sandbox
        cd sandbox/
        ln -s /mnt/lfs4/HFIP/hfv3gfs/role.epic/landda/inputs .
        module load intel/2022.1.2 impi/2022.1.2
        singularity exec -H $PWD $img cp -r /opt/land-DA_workflow .
        cd land-DA_workflow/
        sed -i 's|hera.internal|jet.sing|g' settings_DA_cycle_gdas
        sed -i 's/da-cpu/hfv3gfs/g' submit_cycle.sh
        export USE_SINGULARITY=yes
        pwd
        ./do_submit_cycle.sh settings_DA_cycle_gdas
        '''
      }
    }    
    stage('Run Land DA Workflow on Hera') {
        agent {
          label "hera"
        }
        environment {
        ACCNR = 'nems'
        NODE_PATH = '/scratch1/NCEPDEV/nems/Zachary.Shrader/'
      }
      steps {
          
        cleanWs()
        checkout scm
        sh '''
        pwd
        export img=/scratch1/NCEPDEV/nems/role.epic/containers/ubuntu20.04-intel-ue-landda-v1.1.0.img
        mkdir sandbox
        cd sandbox/
        ln -s /scratch1/NCEPDEV/nems/role.epic/landda/inputs .
        module load intel/2022.1.2 impi/2022.1.2
        singularity exec -H $PWD $img cp -r /opt/land-DA_workflow .
        cd land-DA_workflow/
        sed -i 's|hera.internal|hera.sing|g' settings_DA_cycle_gdas
        sed -i 's/da-cpu/nems/g' submit_cycle.sh
        export USE_SINGULARITY=yes
        pwd
        ./do_submit_cycle.sh settings_DA_cycle_gdas
        '''
      }
    }
  }  
}
