#!/bin/bash
#SBATCH --job-name=offline_noahmp
#SBATCH --account=nems
#SBATCH --qos=batch
#SBATCH --nodes=3
#SBATCH --tasks-per-node=7
#SBATCH --cpus-per-task=1
#SBATCH -t 00:30:00
#SBATCH -o log_noahmp.%j.log
#SBATCH -e err_noahmp.%j.err

############################

ulimit -s unlimited

ctest
