#!/bin/bash
#SBATCH --job-name=offline_noahmp
#SBATCH --account=epic
#SBATCH --qos=debug
#SBATCH --nodes=1
#SBATCH --tasks-per-node=6
#SBATCH --cpus-per-task=1
#SBATCH -t 00:00:30
#SBATCH -o log_noahmp.%j.log
#SBATCH -e err_noahmp.%j.err

############################


module use ../modulefiles && module load landda_hera.intel
ctest
