name: land_da
channels:
  - conda-forge
  - ufs-community
dependencies:
  - pylint=2.17*
  - pytest=7.2*
  - uwtools=2.2.0
  - cartopy=0.23.*
  - matplotlib=3.8.*
  - netcdf4=1.6.*
  - numpy=1.23.*
  - scipy=1.10.*
  - xarray=2022.11.*
