#!/bin/sh

set -ex

############################
# copy restarts to workdir, convert to UFS tile for DA (all members) 

if [[ ${EXP_NAME} == "openloop" ]]; then
    do_jedi="NO"
else
    do_jedi="YES"
    SAVE_TILE="YES"
    LANDDADIR=${CYCLEDIR}/DA_update/
fi

TPATH=${LANDDA_INPUTS}/forcing/${ATMOS_FORC}/orog_files/
YYYY=${CYYYY}
MM=${CMM}
DD=${CDD}
HH=${CHH}
YYYP=${PYYYY}
MP=${PMM}
DP=${PDD}
HP=${PHH}
mem_ens="mem000" 

MEM_WORKDIR=${WORKDIR}/${mem_ens}
MEM_MODL_OUTDIR=${OUTDIR}/${mem_ens}
RSTRDIR=${MEM_WORKDIR}
JEDIWORKDIR=${WORKDIR}/mem000/jedi
FILEDATE=${YYYY}${MM}${DD}.${HH}0000

cd $JEDIWORKDIR

# load modulefiles
#module use modulefiles; module load modules.landda

OBSDIR=${LANDDA_INPUTS}/DA
################################################
# 2. PREPARE OBS FILES
################################################
for obs in "${OBS_TYPES[@]}"; do
    # get the. obs file name
    if [ ${obs} == "GTS" ]; then
	obsfile=$OBSDIR/snow_depth/GTS/data_proc/${YYYY}${MM}/adpsfc_snow_${YYYY}${MM}${DD}${HH}.nc4
	# GHCN are time-stamped at 18. If assimilating at 00, need to use previous day's obs, so that
	# obs are within DA window.
    elif [ $ATMOS_FORC == "era5" ] && [ ${obs} == "GHCN" ]; then
	obsfile=$OBSDIR/snow_depth/GHCN/data_proc/v3/${YYYY}/ghcn_snwd_ioda_${YYYP}${MP}${DP}.nc
    elif [ $ATMOS_FORC == "gswp3" ] && [ ${obs} == "GHCN" ]; then
	obsfile=$OBSDIR/snow_depth/GHCN/data_proc/v3/${YYYY}/fake_ghcn_snwd_ioda_${YYYP}${MP}${DP}.nc
    elif [ ${obs} == "SYNTH" ]; then
	obsfile=$OBSDIR/synthetic_noahmp/IODA.synthetic_gswp_obs.${YYYY}${MM}${DD}${HH}.nc
    else
	echo "do_landDA: Unknown obs type requested ${obs}, exiting"
	exit 1
    fi

    # check obs are available
    if [[ -e $obsfile ]]; then
	echo "do_landDA: $i observations found: $obsfile"
	ln -fs $obsfile  ${obs}_${YYYY}${MM}${DD}${HH}.nc
    else
	echo "${obs} observations not found: $obsfile"
	#    JEDI_TYPES[$ii]="SKIP"
    fi
done
