ACCOUNT: epic
APP: LND
ATMOS_FORC: era5
COLDSTART: 'NO'
COUPLER_CALENDAR: 2
DATE_CYCLE_FREQ_HR: 24
DATE_FIRST_CYCLE: 2025011900
DATE_LAST_CYCLE: 2025012100
DATM_STREAM_FN_LAST_DATE: 2025012100
DO_FREE_FORECAST: 'YES'
DT_ATMOS: 900
DT_RUNSEQ: 3600
envir: test_lnd_smap
EXP_CASE_NAME: lnd_smap_00
FCSTHR: 72
JEDI_ALGORITHM: letkf-oi
LND_CALC_SNET: .true.
LND_IC_TYPE: custom
LND_INITIAL_ALBEDO: 0.25
LND_LAYOUT_X: 1
LND_LAYOUT_Y: 2
LND_OUTPUT_FREQ_SEC: 21600
MED_COUPLING_MODE: ufs.nfrac.aoflux
net: landda
NPROCS_ANALYSIS: 6
NPZ: 127
OBS_GHCN_SNOW: 'NO'
OBS_IMS_SNOW: 'NO'
OBS_SFCSNO: 'NO'
OBS_SMAP: 'YES'
OBS_SMOPS: 'NO'
RES: 96
RUN: landda
SMAP_RAW_WINDOW_SPAN_HALF: 5
WE2E_TEST: 'NO'
