ACCOUNT: epic
APP: LND
ATMOS_FORC: era5
COLDSTART: 'YES'
COUPLER_CALENDAR: 2
DATE_CYCLE_FREQ_HR: 24
DATE_FIRST_CYCLE: 2025011700
DATE_LAST_CYCLE: 2025011800
DATM_STREAM_FN_LAST_DATE: 2025011800
DT_ATMOS: 900
DT_RUNSEQ: 3600
envir: test_lnd_era5_smap
EXP_CASE_NAME: lnd_era5_smap_00
FCSTHR: 24
JEDI_ALGORITHM: letkf-oi
LND_CALC_SNET: .true.
LND_IC_TYPE: custom
LND_INITIAL_ALBEDO: 0.25
LND_LAYOUT_X: 1
LND_LAYOUT_Y: 2
LND_OUTPUT_FREQ_SEC: 21600
MED_COUPLING_MODE: ufs.nfrac.aoflux
model_ver: v2.1.0
net: landda
NPROCS_ANALYSIS: 6
NPZ: 127
OBS_GHCN_SNOW: 'NO'
OBS_IMS_SNOW: 'NO'
OBS_SFCSNO: 'NO'
OBS_SMAP: 'YES'
RES: 96
RUN: landda
WE2E_TEST: 'NO'
