name: Land DA automatic documentation build

on:
  push:
    branches: [ "develop" ]
  pull_request:
    branches: [ "develop" ]

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
    - uses: actions/checkout@v3

    - name: Build HTML
      uses: gabrielfalcao/pyen-action@v18
      with:
        default: "3.11.*"
        command: pip install -U pip
      uses: ammaraskar/sphinx-action@master
      with:
        docs-folder: "doc/"
        pre-build-command: "python --version;python -m pip install --upgrade pip"

    - name: Upload artifacts
      uses: actions/upload-artifact@v3
      with:
        name: html-docs
        path: doc/build/html/
        
    - name: Deploy
      uses: peaceiris/actions-gh-pages@v3
      if: github.ref == 'refs/heads/develop'
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}
        publish_dir: doc/build/html/
